image: oraichain/foundation-cw-gitpod:0.11.8

vscode:
  extensions:
    - rust-lang.rust
    - matklad.rust-analyzer
    - oraichain.cosmwasm-ide

tasks:
  - name: Dependencies & Build
    init: |
      cargo build
